on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Push to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: kiniku90
          password: Kinikumuda2020

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kiniku90/backend-api:propertyexpo-api
          no-cache: true

      # - name: curl
      #   uses: wei/curl@master
      #   with:
      #     args: -X POST http://gojay.co.id:9000/api/webhooks/0027e7fa-1ecd-465a-a08d-114fbf4d234c

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
